name: Gradle Build and Test Cover Agent Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test Cover Agent Plugin
        working-directory: cover-agent-plugin
        run: ../gradlew clean build --stacktrace --info

      - name: Run Check for Cover Agent Plugin
        working-directory: cover-agent-plugin
        run: ../gradlew check

      - name: Generate Jacoco Coverage Report
        working-directory: cover-agent-plugin
        run: ../gradlew jacocoTestReport

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: cover-agent-plugin/build/reports

      - name: Upload Code Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: build

      - name: Clone Wiki Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Copy JaCoCo Report to Wiki
        run: |
          mkdir -p ${{ github.repository }}.wiki/JacocoCoverage
          cp -r build/customJacocoReportDir/html/* ${{ github.repository }}.wiki/JacocoCoverage/

      - name: Copy Unit Test Report to Wiki
        run: |
          mkdir -p ${{ github.repository }}.wiki/UnitTests
          cp -r cover-agent-plugin/build/reports/tests/test/* ${{ github.repository }}.wiki/UnitTests/

      - name: Commit and Push JaCoCo Report to Wiki
        run: |
          cd ${{ github.repository }}.wiki
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add JacocoCoverage/
          git add UnitTests/
          git commit -m "Updated JaCoCo/UnitTests report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}